/* ORÍKÌ AI — curated Chinese AI catalogue
 * Additional directory records are kept separate from data.js so the core
 * catalogue remains easy to maintain. All records use the same schema as
 * window.ORIKI_DATA.ais and are appended only when their id is not present.
 */
(function () {
  const chinaAIs = [
    {id:'kimi',name:'KIMI',provider:'Moonshot AI',country:'China',type:'General AI',category:'Agentic AI',capabilities:['research','reasoning','coding','writing','analysis','search','build'],purposes:['research','create','build','analyse'],bestFor:'Long-context research, agentic work, coding and complex knowledge tasks',pricing:'Free / Paid plans / API',platforms:['Web','Desktop','Mobile','API'],description:'An agentic AI workspace from Moonshot AI with long-context reasoning, research, coding and automation capabilities.',url:'https://www.kimi.com/',status:'Active'},
    {id:'glm',name:'GLM',provider:'Z.ai / Zhipu AI',country:'China',type:'General AI',category:'Reasoning',capabilities:['reasoning','coding','research','writing','analysis','build'],purposes:['research','build','create','analyse'],bestFor:'Reasoning, coding, agents and Chinese-language knowledge work',pricing:'Free / Paid plans / API',platforms:['Web','API','Cloud','Local/Open Models'],description:'Z.ai\'s GLM family of general and reasoning models for chat, coding, agents and enterprise development.',url:'https://z.ai/',status:'Active'},
    {id:'minimax',name:'MINIMAX',provider:'MiniMax',country:'China',type:'Multimodal AI',category:'Multimodal',capabilities:['reasoning','coding','writing','analysis','create','audio','image','video'],purposes:['research','create','build','analyse'],bestFor:'Multimodal work, coding, agents, voice, music and video',pricing:'Free / Paid plans / API',platforms:['Web','API','Cloud','Mobile'],description:'A multimodal AI ecosystem spanning language, coding, agents, video, speech and music generation.',url:'https://www.minimax.io/',status:'Active'},
    {id:'doubao',name:'DOUBAO',provider:'ByteDance',country:'China',type:'General AI',category:'Assistant',capabilities:['reasoning','writing','research','analysis','create','image','audio'],purposes:['research','create','analyse'],bestFor:'Consumer assistance, Chinese-language work and multimodal creation',pricing:'Free / Paid features',platforms:['Web','Mobile'],description:'ByteDance\'s consumer AI assistant and multimodal model ecosystem for conversation, creation and productivity.',url:'https://www.doubao.com/',status:'Active'},
    {id:'ernie',name:'ERNIE',provider:'Baidu',country:'China',type:'General AI',category:'General',capabilities:['reasoning','writing','research','search','analysis','create','coding'],purposes:['research','create','build','analyse'],bestFor:'Chinese-language knowledge work, search, writing and enterprise AI',pricing:'Free / Paid plans / API',platforms:['Web','API','Cloud','Mobile'],description:'Baidu\'s ERNIE family of foundation models and AI services for reasoning, search, content creation and enterprise use.',url:'https://ernie.baidu.com/',status:'Active'},
    {id:'hunyuan',name:'HUNYUAN',provider:'Tencent',country:'China',type:'General AI',category:'Multimodal',capabilities:['reasoning','coding','writing','analysis','create','image','video'],purposes:['research','create','build','analyse'],bestFor:'Multimodal generation, coding and Tencent ecosystem applications',pricing:'Free / API / Enterprise',platforms:['Web','API','Cloud','Local/Open Models'],description:'Tencent\'s foundation-model family supporting language, multimodal understanding, coding and generative applications.',url:'https://hunyuan.tencent.com/',status:'Active'},
    {id:'baichuan',name:'BAICHUAN',provider:'Baichuan AI',country:'China',type:'General AI',category:'Language Models',capabilities:['reasoning','writing','research','analysis','coding'],purposes:['research','create','build','analyse'],bestFor:'Chinese-language reasoning, enterprise knowledge and model development',pricing:'API / Enterprise / Model access',platforms:['Web','API','Cloud','Local/Open Models'],description:'A Chinese foundation-model family focused on language intelligence, reasoning and enterprise applications.',url:'https://www.baichuan-ai.com/',status:'Active'},
    {id:'yi',name:'YI',provider:'01.AI',country:'China',type:'General AI',category:'Open Models',capabilities:['reasoning','coding','writing','analysis','multilingual'],purposes:['research','create','build','analyse'],bestFor:'Open-model development, multilingual language tasks and coding',pricing:'Free / API / Model access',platforms:['API','Cloud','Local/Open Models'],description:'01.AI\'s Yi family of foundation models for language understanding, reasoning and development.',url:'https://www.01.ai/',status:'Active'},
    {id:'step',name:'STEP',provider:'StepFun',country:'China',type:'Reasoning AI',category:'Reasoning',capabilities:['reasoning','coding','research','analysis','vision'],purposes:['research','build','analyse'],bestFor:'Advanced reasoning, coding and multimodal model development',pricing:'API / Enterprise',platforms:['API','Cloud','Local/Open Models'],description:'StepFun\'s foundation-model family focused on reasoning, coding and multimodal intelligence.',url:'https://www.stepfun.com/',status:'Active'},
    {id:'internlm',name:'INTERNLM',provider:'Shanghai AI Laboratory',country:'China',type:'Foundation AI',category:'Open Models',capabilities:['reasoning','coding','research','analysis','multimodal'],purposes:['research','build','analyse'],bestFor:'AI research, open-model development and multimodal experimentation',pricing:'Free / Open Models',platforms:['Web','API','Local/Open Models'],description:'An open foundation-model ecosystem from Shanghai AI Laboratory for research and AI development.',url:'https://internlm.intern-ai.org.cn/',status:'Active'},
    {id:'spark',name:'SPARK',provider:'iFLYTEK',country:'China',type:'General AI',category:'Language',capabilities:['writing','reasoning','research','analysis','coding','audio'],purposes:['research','create','analyse','build'],bestFor:'Chinese-language productivity, education, speech and enterprise applications',pricing:'Free / Paid / Enterprise',platforms:['Web','API','Mobile','Cloud'],description:'iFLYTEK\'s Spark AI ecosystem combining language, reasoning and speech capabilities for Chinese users and enterprises.',url:'https://www.iflytek.com/',status:'Active'},
    {id:'sensenova',name:'SENSENOVA',provider:'SenseTime',country:'China',type:'Multimodal AI',category:'Enterprise AI',capabilities:['reasoning','analysis','vision','image','video','coding','create'],purposes:['research','create','build','analyse'],bestFor:'Enterprise multimodal AI, computer vision and content generation',pricing:'Free trial / Paid / Enterprise',platforms:['Web','API','Cloud'],description:'SenseTime\'s foundation-model platform combining multimodal understanding, generation and enterprise AI applications.',url:'https://www.sensetime.com/en/',status:'Active'},
    {id:'pangu',name:'PANGU',provider:'Huawei',country:'China',type:'Enterprise AI',category:'Foundation Models',capabilities:['reasoning','analysis','coding','vision','industry','forecasting'],purposes:['research','build','analyse'],bestFor:'Industrial, enterprise and sector-specific AI applications',pricing:'Enterprise / Cloud',platforms:['Cloud','API','Enterprise'],description:'Huawei\'s Pangu foundation-model ecosystem for enterprise and industry-specific AI applications.',url:'https://www.huawei.com/en/technology/pangu',status:'Active'},
    {id:'360-zhinao',name:'360 ZHINAO',provider:'Qihoo 360',country:'China',type:'General AI',category:'Assistant',capabilities:['writing','research','search','reasoning','analysis','create'],purposes:['research','create','analyse'],bestFor:'Chinese-language search, knowledge work and consumer assistance',pricing:'Free / Product-dependent',platforms:['Web','Mobile','Cloud'],description:'Qihoo 360\'s Chinese AI assistant and large-model ecosystem for search, knowledge and content tasks.',url:'https://ai.360.cn/',status:'Active'},
    {id:'longcat',name:'LONGCAT',provider:'Meituan',country:'China',type:'General AI',category:'Open Models',capabilities:['reasoning','coding','writing','analysis','agents'],purposes:['research','build','create','analyse'],bestFor:'Agentic workflows, reasoning and open-model experimentation',pricing:'Free / Model access',platforms:['Web','API','Local/Open Models'],description:'Meituan\'s LongCat model family for general intelligence, reasoning and agentic applications.',url:'https://longcat.ai/',status:'Active'},
    {id:'hailuo',name:'HAILUO AI',provider:'MiniMax',country:'China',type:'Video AI',category:'Video',capabilities:['create','video','image','audio'],purposes:['create'],bestFor:'Generative video, image-to-video and creative storytelling',pricing:'Free / Paid plans',platforms:['Web','Mobile'],description:'MiniMax\'s generative media platform for AI video and visual creation.',url:'https://hailuoai.video/',status:'Active'},
    {id:'vidu',name:'VIDU',provider:'ShengShu Technology',country:'China',type:'Video AI',category:'Video',capabilities:['create','video','image','design'],purposes:['create'],bestFor:'Image-to-video, reference consistency and generative video production',pricing:'Free / Paid plans',platforms:['Web','API'],description:'An AI image and video creation platform specialising in reference-based and generative video workflows.',url:'https://www.vidu.com/',status:'Active'},
    {id:'wan',name:'WAN',provider:'Alibaba',country:'China',type:'Generative Media AI',category:'Video',capabilities:['create','video','image','design'],purposes:['create'],bestFor:'Open generative video and image model development',pricing:'Free / Open Models / API',platforms:['Web','API','Local/Open Models'],description:'Alibaba\'s Wan family of open generative models for image and video creation.',url:'https://wan.video/',status:'Active'},
    {id:'tongyi-wanxiang',name:'TONGYI WANXIANG',provider:'Alibaba',country:'China',type:'Image AI',category:'Image',capabilities:['create','image','design','edit'],purposes:['create'],bestFor:'AI image generation, editing and visual design',pricing:'Free / Paid / API',platforms:['Web','API','Cloud'],description:'Alibaba\'s generative visual intelligence platform for image creation and editing.',url:'https://tongyi.aliyun.com/',status:'Active'},
    {id:'jimeng',name:'JIMENG AI',provider:'ByteDance',country:'China',type:'Creative AI',category:'Image & Video',capabilities:['create','image','video','design'],purposes:['create'],bestFor:'Chinese-language image, video and creative content generation',pricing:'Free / Paid plans',platforms:['Web','Mobile'],description:'ByteDance\'s creative-generation platform for producing AI images, video and visual content.',url:'https://jimeng.jianying.com/',status:'Active'},
    {id:'cogview',name:'COGVIEW',provider:'Z.ai / Zhipu AI',country:'China',type:'Image AI',category:'Image',capabilities:['create','image','design'],purposes:['create'],bestFor:'Text-to-image generation and multimodal model development',pricing:'API / Model access',platforms:['API','Cloud','Local/Open Models'],description:'Z.ai\'s CogView family of text-to-image generation models.',url:'https://z.ai/',status:'Active'}
  ];

  if (window.ORIKI_DATA && Array.isArray(window.ORIKI_DATA.ais)) {
    const existing = new Set(window.ORIKI_DATA.ais.map(ai => ai.id));
    window.ORIKI_DATA.ais.push(...chinaAIs.filter(ai => !existing.has(ai.id)));
  }
})();
