window.ORIKI_DATA = {
  ais: [
    {id:'chatgpt',name:'CHATGPT',provider:'OpenAI',type:'General AI',category:'General',capabilities:['research','coding','writing','reasoning','analysis','search','create'],purposes:['research','create','build','analyse'],description:'A versatile general-purpose intelligence for research, writing, coding, analysis and everyday work.',url:'https://chatgpt.com/'},
    {id:'claude',name:'CLAUDE',provider:'Anthropic',type:'General AI',category:'General',capabilities:['research','coding','writing','reasoning','analysis'],purposes:['research','create','build','analyse'],description:'A strong choice for long-form writing, document analysis, reasoning and software development.',url:'https://claude.ai/'},
    {id:'gemini',name:'GEMINI',provider:'Google',type:'General AI',category:'Multimodal',capabilities:['research','analysis','reasoning','coding','search','create'],purposes:['research','create','build','analyse'],description:'Google intelligence combining text, code and multimodal understanding with broad ecosystem integration.',url:'https://gemini.google.com/'},
    {id:'perplexity',name:'PERPLEXITY',provider:'Perplexity',type:'Research AI',category:'Research',capabilities:['research','search','analysis'],purposes:['research','analyse'],description:'An answer engine built around web research, source synthesis and current information.',url:'https://www.perplexity.ai/'},
    {id:'grok',name:'GROK',provider:'xAI',type:'General AI',category:'Real-time',capabilities:['research','reasoning','search'],purposes:['research','analyse'],description:'A conversational intelligence focused on reasoning and access to current public information.',url:'https://grok.com/'},
    {id:'copilot',name:'COPILOT',provider:'Microsoft',type:'Productivity AI',category:'Productivity',capabilities:['writing','coding','analysis','research'],purposes:['research','create','build','analyse'],description:'AI assistance integrated across Microsoft productivity and development workflows.',url:'https://copilot.microsoft.com/'},
    {id:'cursor',name:'CURSOR',provider:'Anysphere',type:'Coding AI',category:'Coding',capabilities:['coding','build','analysis','reasoning'],purposes:['build','analyse'],description:'An AI-first development environment designed for building and understanding software.',url:'https://www.cursor.com/'},
    {id:'midjourney',name:'MIDJOURNEY',provider:'Midjourney',type:'Image AI',category:'Image',capabilities:['create','image'],purposes:['create'],description:'Generative intelligence focused on visual creation, concept development and image making.',url:'https://www.midjourney.com/'},
    {id:'deepseek',name:'DEEPSEEK',provider:'DeepSeek',type:'General AI',category:'Reasoning',capabilities:['reasoning','coding','research','analysis'],purposes:['research','build','analyse'],description:'General-purpose intelligence with a strong focus on reasoning, coding and technical problem solving.',url:'https://www.deepseek.com/'},
    {id:'mistral',name:'MISTRAL',provider:'Mistral AI',type:'General AI',category:'Open Models',capabilities:['reasoning','coding','writing','analysis'],purposes:['create','build','analyse'],description:'A family of general and specialist AI systems with strong language and coding capabilities.',url:'https://mistral.ai/'},
    {id:'qwen',name:'QWEN',provider:'Alibaba Cloud',type:'General AI',category:'Multimodal',capabilities:['reasoning','coding','writing','analysis','create'],purposes:['create','build','analyse'],description:'A broad family of language and multimodal models for reasoning, coding and creation.',url:'https://qwen.ai/'},
    {id:'notebooklm',name:'NOTEBOOKLM',provider:'Google',type:'Research AI',category:'Documents',capabilities:['research','analysis','reasoning'],purposes:['research','analyse'],description:'A source-grounded research workspace for understanding and interrogating your documents.',url:'https://notebooklm.google.com/'},
    {id:'github-copilot',name:'GITHUB COPILOT',provider:'GitHub',type:'Coding AI',category:'Coding',capabilities:['coding','build','reasoning'],purposes:['build'],description:'AI coding assistance integrated into the software development workflow.',url:'https://github.com/features/copilot'},
    {id:'replit',name:'REPLIT',provider:'Replit',type:'Coding AI',category:'Build',capabilities:['coding','build','create'],purposes:['build','create'],description:'An AI-assisted development platform for building and deploying applications from the browser.',url:'https://replit.com/'},
    {id:'windsurf',name:'WINDSURF',provider:'Cognition',type:'Coding AI',category:'Coding',capabilities:['coding','build','reasoning'],purposes:['build'],description:'An agentic coding environment designed to help developers build software with AI.',url:'https://windsurf.com/'},
    {id:'ideogram',name:'IDEOGRAM',provider:'Ideogram',type:'Image AI',category:'Image',capabilities:['create','image'],purposes:['create'],description:'Visual generation focused on image creation, typography and design concepts.',url:'https://ideogram.ai/'},
    {id:'adobe-firefly',name:'FIREFLY',provider:'Adobe',type:'Image AI',category:'Creative',capabilities:['create','image'],purposes:['create'],description:'Creative generative AI for image, design and production workflows across Adobe tools.',url:'https://firefly.adobe.com/'},
    {id:'runway',name:'RUNWAY',provider:'Runway',type:'Video AI',category:'Video',capabilities:['create','video'],purposes:['create'],description:'Generative video intelligence for creating, transforming and editing visual media.',url:'https://runwayml.com/'},
    {id:'kling',name:'KLING',provider:'Kuaishou',type:'Video AI',category:'Video',capabilities:['create','video'],purposes:['create'],description:'Generative video intelligence for cinematic creation and visual storytelling.',url:'https://klingai.com/'},
    {id:'elevenlabs',name:'ELEVENLABS',provider:'ElevenLabs',type:'Audio AI',category:'Voice',capabilities:['create','audio'],purposes:['create'],description:'Voice and audio intelligence for speech generation, narration and conversational experiences.',url:'https://elevenlabs.io/'},
    {id:'suno',name:'SUNO',provider:'Suno',type:'Audio AI',category:'Music',capabilities:['create','audio'],purposes:['create'],description:'Generative music intelligence for creating songs and musical ideas from prompts.',url:'https://suno.com/'},
    {id:'gamma',name:'GAMMA',provider:'Gamma',type:'Creative AI',category:'Presentations',capabilities:['create','writing','design'],purposes:['create'],description:'AI-powered creation for presentations, documents and visual communication.',url:'https://gamma.app/'},
    {id:'canva',name:'CANVA AI',provider:'Canva',type:'Creative AI',category:'Design',capabilities:['create','design','writing'],purposes:['create'],description:'AI-assisted design and content creation inside Canva’s visual workspace.',url:'https://www.canva.com/'},
    {id:'elicit',name:'ELICIT',provider:'Elicit',type:'Research AI',category:'Academic',capabilities:['research','search','analysis','writing'],purposes:['research','analyse'],description:'Research intelligence designed to help discover, screen and synthesize academic literature.',url:'https://elicit.com/'},
    {id:'consensus',name:'CONSENSUS',provider:'Consensus',type:'Research AI',category:'Academic',capabilities:['research','search','analysis'],purposes:['research','analyse'],description:'Academic search intelligence that helps find evidence and synthesize findings from research papers.',url:'https://consensus.app/'},
    {id:'meta-ai',name:'META AI',provider:'Meta',type:'General AI',category:'Assistant',capabilities:['writing','research','create','reasoning'],purposes:['research','create'],description:'General-purpose AI assistance integrated across Meta products and experiences.',url:'https://www.meta.ai/'},
    {id:'huggingface',name:'HUGGING FACE',provider:'Hugging Face',type:'AI Platform',category:'Models',capabilities:['coding','research','analysis','create'],purposes:['research','build','analyse','create'],description:'A broad ecosystem for discovering, using and building with open AI models and datasets.',url:'https://huggingface.co/'},
    {id:'jasper',name:'JASPER',provider:'Jasper',type:'Business AI',category:'Marketing',capabilities:['writing','create','analysis'],purposes:['create','analyse'],description:'Business-focused AI for marketing content, campaigns and brand workflows.',url:'https://www.jasper.ai/'}
  ],
  purposes: {
    research:{title:'RESEARCH',text:'Find. Investigate. Understand.',capabilities:['research','search','analysis']},
    create:{title:'CREATE',text:'Write. Design. Imagine.',capabilities:['writing','create','image','video','audio','design']},
    build:{title:'BUILD',text:'Code. Engineer. Develop.',capabilities:['coding','build','reasoning']},
    analyse:{title:'ANALYSE',text:'Understand data. Solve complexity.',capabilities:['analysis','reasoning','research']}
  },
  capabilityMeta: {
    research:'Find, investigate and synthesize knowledge.',search:'Find current information and sources.',writing:'Draft, edit and transform written work.',coding:'Write, understand and debug software.',reasoning:'Work through difficult multi-step problems.',analysis:'Read data, documents and complex problems.',create:'Generate new creative work.',image:'Generate and transform images.',video:'Generate and transform video.',audio:'Generate speech, music and sound.',design:'Create visual communication and design.',build:'Engineer and develop software.'
  }
};