const ORIKI_LIVE_AI = {
  cacheKey: 'oriki-live-ai-catalogue-v1', cacheTtlMs: 10 * 60 * 1000, models: [], sources: {}, status: 'idle', lastUpdated: null,
  async load({force=false}={}) {
    this.status='loading'; this.emit();
    if(!force){const cached=this.readCache(); if(cached){Object.assign(this,cached);this.status='ready';this.emit();return this.models;}}
    const [o,h]=await Promise.allSettled([this.fetchOpenRouter(),this.fetchHuggingFace()]);
    const open=o.status==='fulfilled'?o.value:[], hf=h.status==='fulfilled'?h.value:[];
    this.models=dedupeModels([...open,...hf]); this.lastUpdated=new Date().toISOString(); this.status=this.models.length?'ready':'error'; this.writeCache(); this.emit(); return this.models;
  },
  async fetchOpenRouter(){try{const r=await fetch('https://openrouter.ai/api/v1/models',{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();const m=(p.data||[]).map(normalizeOpenRouter).filter(Boolean);this.sources.openrouter={status:'ready',count:m.length};return m;}catch(e){this.sources.openrouter={status:'error',count:0,error:e.message};console.error('[ORÍKÌ] OpenRouter failed',e);return[];}},
  async fetchHuggingFace(){try{const r=await fetch('https://huggingface.co/api/models?pipeline_tag=text-generation&sort=downloads&direction=-1&limit=200&full=false',{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();const m=(p||[]).map(normalizeHuggingFace).filter(Boolean);this.sources.huggingface={status:'ready',count:m.length};return m;}catch(e){this.sources.huggingface={status:'error',count:0,error:e.message};console.error('[ORÍKÌ] Hugging Face failed',e);return[];}},
  readCache(){try{const c=JSON.parse(localStorage.getItem(this.cacheKey)||'null');if(!c?.lastUpdated||!Array.isArray(c.models)||Date.now()-new Date(c.lastUpdated).getTime()>this.cacheTtlMs)return null;return c;}catch{return null;}},
  writeCache(){try{localStorage.setItem(this.cacheKey,JSON.stringify({models:this.models,sources:this.sources,lastUpdated:this.lastUpdated}));}catch{}},
  emit(){window.dispatchEvent(new CustomEvent('oriki:live-ai',{detail:{status:this.status,count:this.models.length,sources:this.sources,lastUpdated:this.lastUpdated}}));}
};
function normalizeOpenRouter(m){if(!m?.id||!m?.name)return null;const a=m.architecture||{},i=a.input_modalities||[],o=a.output_modalities||[],p=m.supported_parameters||[],c=new Set();if(i.includes('text')||o.includes('text'))c.add('writing');if(i.some(x=>['image','video','audio','file'].includes(x)))c.add('multimodal');if(p.includes('tools')||p.includes('tool_choice'))c.add('tools');if(p.includes('reasoning')||p.includes('reasoning_effort')||m.reasoning)c.add('reasoning');if(p.includes('structured_outputs')||p.includes('response_format'))c.add('structured-output');if(p.includes('web_search'))c.add('search');if(o.includes('image'))c.add('image-generation');return{id:`openrouter:${m.id}`,name:m.name,provider:m.id.split('/')[0]||'OpenRouter',source:'OpenRouter',sourceId:m.id,type:'AI Model',category:'Model',description:m.description||'Model available through OpenRouter.',capabilities:[...c],purposes:c.has('reasoning')?['research','analyse','build']:['research','create','build'],contextLength:m.context_length||null,pricing:m.pricing||{},inputModalities:i,outputModalities:o,supportedParameters:p,url:`https://openrouter.ai/${encodeURIComponent(m.id)}`};}
function normalizeHuggingFace(m){if(!m?.id)return null;const tags=m.tags||[],c=new Set(['open-source']);if(tags.some(t=>/text-generation|text2text|causal-lm/i.test(t)))c.add('writing');if(tags.some(t=>/image|vision|multimodal/i.test(t)))c.add('multimodal');if(tags.some(t=>/code|coding|programming/i.test(t)))c.add('coding');if(tags.some(t=>/reasoning/i.test(t)))c.add('reasoning');return{id:`huggingface:${m.id}`,name:m.id.split('/').pop()||m.id,provider:m.id.includes('/')?m.id.split('/')[0]:'Hugging Face',source:'Hugging Face',sourceId:m.id,type:'Open Model',category:'Open Source',description:`Open model on Hugging Face. Downloads: ${Number(m.downloads||0).toLocaleString()}.`,capabilities:[...c],purposes:['research','create','build','analyse'],contextLength:null,pricing:{},inputModalities:['text'],outputModalities:['text'],downloads:m.downloads||0,likes:m.likes||0,url:`https://huggingface.co/${encodeURIComponent(m.id)}`};}
function dedupeModels(models){const s=new Set();return models.filter(m=>{const k=`${m.source}:${m.sourceId}`.toLowerCase();if(s.has(k))return false;s.add(k);return true;});}
window.ORIKI_LIVE_AI=ORIKI_LIVE_AI;window.addEventListener('DOMContentLoaded',()=>ORIKI_LIVE_AI.load());
