/* ORÍKÌ AI — Live News presentation layer
 * Uses the normalized feed records generated by scripts/oriki_feed_scanner.py.
 * No API credentials are exposed in the browser.
 */
(function () {
  const esc = value => String(value ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fmtDate = value => {
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? String(value || '') : d.toLocaleDateString('en-GB', {day:'2-digit', month:'short', year:'numeric'});
  };

  function card(item) {
    const image = item.image ? `<div class="news-card-image"><img src="${esc(item.image)}" alt="" loading="lazy" onerror="this.closest('.news-card-image').remove()"></div>` : '';
    return `<article class="news-card ${image ? 'has-image' : ''}" data-id="${esc(item.id)}">
      ${image}
      <div class="news-card-body">
        <div class="news-card-top"><span class="news-category">${esc(item.category)}</span><span>${esc(fmtDate(item.date))}</span></div>
        <h3>${esc(item.title)}</h3>
        <p>${esc(item.summary || 'Read the original report from the publisher.')}</p>
        <div class="news-source">${esc(item.source)} <span>→</span></div>
      </div>
    </article>`;
  }

  function renderNews() {
    const N = window.ORIKI_NEWS || [];
    const categories = ['ALL','BREAKING','NEW RELEASES','MODELS','TOOLS','RESEARCH','BUSINESS','AFRICA','POLICY','ROBOTICS','OPEN SOURCE'];
    return `<div class="news-hero"><div><p class="eyebrow">THE INTELLIGENCE LANDSCAPE</p><h2>WHAT<br><span>CHANGED?</span></h2><p class="muted">ORÍKÌ aggregates curated AI reporting, research, official lab announcements and public news feeds into one intelligence stream.</p></div><div class="news-status"><strong>LIVE INTELLIGENCE FEED</strong><span>${N.length} indexed stories</span><small>RSS + PUBLIC API SOURCES · AUTOMATED REFRESH</small></div></div>
      <div class="news-toolbar"><select id="newsFilter" aria-label="Filter news category">${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select><span id="newsCount">${N.length} STORIES</span></div>
      <div class="news-grid" id="newsGrid">${N.map(card).join('')}</div>`;
  }

  function filterNews() {
    const N = window.ORIKI_NEWS || [];
    const value = document.getElementById('newsFilter')?.value || 'ALL';
    const items = value === 'ALL' ? N : N.filter(n => n.category === value);
    const grid = document.getElementById('newsGrid');
    if (!grid) return;
    grid.innerHTML = items.length ? items.map(card).join('') : '<div class="empty">No stories in this category yet.</div>';
    const count = document.getElementById('newsCount');
    if (count) count.textContent = `${items.length} STORIES`;
    bind();
  }

  function openNews(id) {
    const item = (window.ORIKI_NEWS || []).find(n => n.id === id);
    if (!item) return;
    const modal = document.createElement('div');
    modal.className = 'news-modal';
    const image = item.image ? `<div class="news-modal-image"><img src="${esc(item.image)}" alt="" onerror="this.parentElement.remove()"></div>` : '';
    modal.innerHTML = `<div class="news-modal-box">${image}<button class="close news-close">×</button><p class="eyebrow">${esc(item.category)} · ${esc(fmtDate(item.date))}</p><h2>${esc(item.title)}</h2><p class="muted">${esc(item.summary || '')}</p><p class="news-source">${esc(item.source)}</p><a class="btn gold" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">READ SOURCE</a></div>`;
    document.body.appendChild(modal);
    modal.querySelector('.news-close').onclick = () => modal.remove();
    modal.onclick = e => { if (e.target === modal) modal.remove(); };
  }

  function bind() {
    document.querySelectorAll('.news-card').forEach(el => el.onclick = () => openNews(el.dataset.id));
    const filter = document.getElementById('newsFilter');
    if (filter) filter.onchange = filterNews;
  }

  // Replace the existing global news functions after script.js has loaded.
  window.news = renderNews;
  window.newsCard = card;
  window.filterNews = filterNews;
  window.openNews = openNews;
  window.ORIKI_bindLiveNews = bind;
})();
